#!/bin/bash

modes="Run\nWindow Switcher\nEmoji Picker"

selected_mode=$(echo -e "$modes" | rofi -dmenu -i -p "Select Mode:")

# Run the selected mode
case "$selected_mode" in
    "Run")
        rofi -show run
        ;;
    "Window Switcher")
        rofi -show window
        ;;
    "Emoji Picker")
        rofi -show emoji
        ;;
    *)
        echo "Invalid selection"
        ;;
esac
